---
# tasks file for unbound
- name: install requirements
  package:
    name: "{{ unbound_requirements }}"
    state: present
  register: unbound_install_requirements
  until: unbound_install_requirements is succeeded
  retries: 3

- name: download archive
  unarchive:
    src: "https://nlnetlabs.nl/downloads/unbound/unbound-latest.tar.gz"
    dest: "{{ unbound_temporary_directory }}"
    list_files: yes
    remote_src: yes
  register: unbound_download_archive
  until: unbound_download_archive is succeeded
  retries: 3

- name: save unarchived directory
  set_fact:
    # unbound_chdir: "{{ unbound_find_unarchived_directory.files[0].path }}"
    unbound_chdir: "{{ unbound_temporary_directory }}/{{ unbound_download_archive.files | first }}"

- name: configure
  command: ./configure --enable-systemd
  args:
    chdir: "{{ unbound_chdir }}"
    creates: "{{ unbound_chdir }}/Makefile"

- name: make
  command: make
  args:
    chdir: "{{ unbound_chdir }}"
    creates: unbound

- name: make install
  command: make install
  args:
    chdir: "{{ unbound_chdir }}"
    creates: /usr/local/sbin/unbound

- name: make group unbound
  group:
    name: unbound
    system: yes

- name: make user unbound
  user:
    name: unbound
    group: unbound
    system: yes

- name: install service
  copy:
    src: "{{ unbound_chdir }}/contrib/unbound.service"
    dest: /etc/systemd/system/unbound.service
    remote_src: yes
  notify:
    - systemctl daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: configure unbound
  template:
    src: unbound.conf.j2
    dest: /usr/local/etc/unbound/unbound.conf
  notify:
    - restart unbound

- name: start and enable unbound
  block:
    - name: start and enable unbound
      service:
        name: unbound
        state: started
        enabled: yes
      register: unbound_start_and_enable_unbound
  rescue:
    - name: show registered results
      debug:
        msg: "{{ unbound_start_and_enable_unbound }}"
    - name: save journalectl -xe output
      command: journalctl -xe
      register: unbound_save_jounalct_xe_output
    - name: show registered results
      debug:
        msg: "{{ unbound_save_jounalct_xe_output }}"
