---
# handlers file for unbound
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart unbound
  service:
    name: "{{ unbound_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
